svceClubMgmt/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('',include('svceClubMgmtApp.urls')),
    path('admin/', admin.site.urls),
]

svceClubMgmtApp/urls.py
from django.urls import path

from . import views
app_name='svceClubMgmtApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('login',views.signin,name='signin'),
    path('register',views.signup,name='register'),
    path('logout',views.signout,name='logout'),
    path('club/<str:nm>',views.club,name='clubPage'),
    path('president/<str:nm>',views.club,name='presidenthome'),
    path('president/<str:nm>/e_a_r',views.actrec,name='enable_actively_recruit'),
    path('president/<str:nm>/e_a_r',views.actrec,name='disable_actively_recruit'),
    path('club/<str:nm>/registration',views.register,name='recruit'),
    path('club/<str:nm>/requirements/',views.requirements,name='requirements'),
]

svceClubMgmtApp/models.py
from unicodedata import name
from django.db import models

# Create your models here.
class Club(models.Model):
    name=models.CharField(max_length=30)
    logo_url=models.CharField(max_length=30)
    about=models.CharField(max_length=300)
    president_username=models.CharField(default='shri',max_length=30)
    recruiting=models.IntegerField(default=0)

class Volunteers(models.Model):
    name=models.CharField(max_length=30)
    branch=models.CharField(max_length=30)
    yos=models.IntegerField()
    sec=models.CharField(max_length=2)
    regno=models.CharField(max_length=10)
    phoneno=models.CharField(max_length=11)
    clgmailid=models.CharField(max_length=50)
    linkedin=models.CharField(max_length=100)
    clubname=models.CharField(default='no club',max_length=20)

    

svceClubMgmtApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password
from django.urls import reverse
from .models import Club, Volunteers

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        un=request.user.username
        user=User.objects.filter(username=un)[0]
        if user is not None and user.is_superuser:
            clubname=Club.objects.filter(president_username=un)[0].name
            return HttpResponseRedirect(reverse('svceClubMgmtApp:presidenthome',kwargs={'nm':clubname}))
    clublist=Club.objects.all()
    return render(request,'index.html',{'clublist':clublist})

def signup(request):
    if request.method == "POST":
        username = request.POST['username']
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']
        
        if User.objects.filter(username=username):
            messages.error(request, "Username already exist! Please try some other username.")
            return redirect('home')
        
        if User.objects.filter(email=email).exists():
            messages.error(request, "Email Already Registered!!")
            return redirect('home')
        
        if len(username)>20:
            messages.error(request, "Username must be under 20 charcters!!")
            return redirect('home')
        
        if pass1 != pass2:
            messages.error(request, "Passwords didn't matched!!")
            return redirect('home')
        
        if not username.isalnum():
            messages.error(request, "Username must be Alpha-Numeric!!")
            return redirect('home')
        
        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name = fname
        myuser.last_name = lname
        myuser.save()
        return HttpResponseRedirect('login')
    return render(request,'register.html')

def signin(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            un = request.POST['username']
            pass1 = request.POST['pass1']
            print(un,pass1)
            user=User.objects.filter(username=un)
            if len(user)==1:
                if check_password(pass1,user[0].password):
                    user = authenticate(username=un,password=pass1)
                    print(user)
                    if user is not None:
                        login(request, user)
                        return HttpResponseRedirect(reverse('svceClubMgmtApp:index'))
                    else:
                        print('username or password is wrong')
                        return HttpResponseRedirect('login')
            else:
                print('username or password is wrong')
                return HttpResponseRedirect('login')        
        return render(request, "login.html")
    else:
        return HttpResponseRedirect(reverse('svceClubMgmtApp:index'))

def signout(request):
    logout(request)
    return HttpResponseRedirect(reverse('svceClubMgmtApp:index'))

def club(request,nm):
    if request.user.is_authenticated:
        clublist=Club.objects.filter(name=nm)[0]
        if request.user.is_superuser:
            if not clublist.president_username==request.user.username:
                return HttpResponse('Access denied or Page not found')
    clublist=Club.objects.filter(name=nm)[0]
    print(clublist)
    about=clublist.about
    about_list=about.split('<br>')
    clublist.about=about_list
    return render(request,'clubpage.html',{'clublist':clublist})

def actrec(request,nm):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            club=Club.objects.filter(name=nm)[0]
            username=club.president_username
            if request.user.username==username:
                if(club.recruiting):
                    club.recruiting=0
                else:
                    club.recruiting=1
                club.save()
                return HttpResponseRedirect(reverse('svceClubMgmtApp:clubPage',kwargs={'nm':nm}))
            else:return HttpResponse('access denied!')
        else:return HttpRequest('dont have access for students!')
    else:
        return HttpResponseRedirect(reverse('svceClubMgmtApp:index'))

def register(request,nm):
    if request.method=="POST":
        form=request.POST
        name=form['name']
        branch=form['branch']
        sec=form['section']
        yos=form['year']
        phno=form['phone_number']
        regno=form['reg_num']
        cmid=form['c_mid']
        lp=form['lp']
        vol=Volunteers(name=name,branch=branch,sec=sec,yos=yos,phoneno=phno,regno=regno,clgmailid=cmid,linkedin=lp)
        vol.save()
        return HttpResponseRedirect(reverse('svceClubMgmtApp:club',kwargs={'nm':nm}))
    if request.user.is_authenticated and not request.user.is_superuser:
        clubname=Club.objects.filter(name=nm)[0].name
        return render(request,'registration.html',{'clubname':clubname})

def requirements(request,nm):
    if request.user.is_authenticated and not request.user.is_superuser:
        clublist=Club.objects.filter(name=nm)[0]
        return render(request,'postingpage.html',{'clublist':clublist})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SVCE</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        body{
            background-color: rgb(41, 40, 40);
            color: white;
        }
        nav{
            background-color: rgb(14, 14, 14);
            padding: 20px;
            position: fixed;
            top: 0;
        }
        h2{
            text-align: center;
        }
        nav a{
            color: rgb(255, 255, 255);
        }
        nav a:hover{
            text-decoration: none;
            color: white;
            text-shadow: 2px rgb(191, 23, 23);
        }
        #brand{
            width: fit-content;
            display: inline;
            margin-left: 2px;
            font-weight: bold;
        }
        #navbarNav{
            list-style-type: none;
            width:auto;
            float: right;
        }
        #items{
            margin: 10px;
            position: absolute;
            top: 0;
            right: 0;
            background-color: aliceblue;
            display: none;
            padding: 10px;
        }
        #items a{
            color: black;
        }
        #dropdown:hover #items{
            display: inline;
        }
        #login-form{
            color: black;
            margin-top: 10px;
            margin-left: auto;
            background-color: aliceblue;
            width: 40%;
            padding: 20px;
            border-radius: 2px;

        }
        #register-page{
            color: black;
            margin-top: 10px;
            margin-left: auto;
            background-color: aliceblue;
            width: 40%;
            padding: 20px;
            border-radius: 2px;
        }
        footer{
            position: absolute;
            bottom: 0;
            margin-left: auto;
            margin-right: auto;
            background-color: rgb(223, 188, 34);
            color: black;
            text-align: center;
            width: 100%;
        }
    </style>
</head>
<body>
    <nav class="navbar">
        <div id="brand">
            <a href="/">SVCE Club</a>
        </div>
        <ul classs="navbar-nav" id="navbarNav">
            {%if user.is_authenticated%}
            <div id="dropdown">
                <li class="nav-item">{{user.first_name}}</li>
                <div id="items">
                    <li class="nav-item"><a href="{% url 'svceClubMgmtApp:logout' %}">Logout</a></li>
                </div>                
            </div>
            {%else%}
            <li><a href="{%url 'svceClubMgmtApp:signin'%}">Login</a></li>
            {%endif%}
        </ul>
    </nav>
    {%block signinpage%}{%endblock%}
    {%block register%}{%endblock%}
    {%block index%}{%endblock%}
    {%block clubPage%}{%endblock%}
    {%block postingpage%}{%endblock%}
    {%block registration%}{%endblock%}
</body>
</html>

templates/clubmainpage.html
{%extends 'clubpage.html'%}
{%block clubmainpage%}
<div id="menus" class="clubcontent">
    <a class="items" onclick="showAbout();" href="#">About</a>
    <a class="items" onclick="showEvent();" href="#">Events</a>
    <a class="items" onclick="showUpEve();" href="#">Upcoming Events</a>
</div>
<div id="contents">
    <h1 id="ClubName">{{clublist.name}}</h1> 
    <div  class="clubcontent" id="about">
        <h1 id="ClubName">{{clublist.name}}</h1>   
        <p>
            {%for p in clublist.about%}
            {{p}}<br><br>
            {%endfor%}
        </p>
    </div>
    {%if user.is_authenticated and not user.is_superuser and clublist.recruiting%}
    <div style="text-align: center;">
        <a href="#" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Actively recruiting</a>
    </div>
    {%elif user.is_authenticated and user.is_superuser and clublist.recruiting%}
    <div style="text-align: center;">
        <a href="{%url 'svceClubMgmtApp:enable_actively_recruit' clublist.name%}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Stop Recruitment</a>
    </div>
    {%elif user.is_authenticated and user.is_superuser and not clublist.recruiting%}
    <div style="text-align: center;">
        <a href="{%url 'svceClubMgmtApp:disable_actively_recruit' clublist.name%}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Recruit</a>
    </div>
    {%endif%}
    <div class="clubcontent" id="event">
        <h3>Past Events</h3>
        {%if clublist.name == "ACE"%}
        <div id="aceevents">
            <div class="container">
                    <div class="row">
                    <div><h6><a href="#">INAUGRATION</a></h6></div>
                        <div><p>ACE Team is euphoric 🎉 in announcing its Inauguration Ceremony for this academic year 2021-22</p></div> 
                    </div>
            </div>
        </div>
        {%elif clublist.name == "ACM"%}
        <div id="acmevents">
            <div class="container">
                <div class="row">
                    <div><h6><a href="#">THE MISSING SEMESTER</a></h6></div>
                    <div><p>The Missing Semester was a hands-on workshop conducted by SVCE ACM Student Chapter on the 17th and 18th of October</p></div>
                </div>
            </div>
        </div>
        {%elif clublist.name == "FORESE"%}
        <div id="foreseevents">
            <div><h6><a href="#">FORED</a></h6></div>
            <div><p>For our students who are willing to add more feathers to their caps and are looking to go abroad to pursue higher 
                education, we organize an annual ForED fair in the odd semester</p></div>
        </div>
        {%endif%}
    </div>
    <div class="clubcontent" id="upevents">
        <h3>Upcoming Events</h3>
        <div class="container eventcontainer">
            {%if clublist.name == "ACE"%}
            <div id="aceevent">
                <div class="eventlist">
                    <div><h6><a href="#">INTERRUPT</a></h6></div>
                    <div><p>Interrupt is the National-level Technical Symposium hosted by ACE annually</p></div>
                </div>
            </div>
            {%elif clublist.name == "ACM"%}
            <div id="acmevent">
                <div class="eventlist">
                    <div><h6><a href="#">RAPID FIRE</a></h6></div>
                    <div><p>Rapid fire was a problem-solving contest conducted by SVCE ACMW Student Chapter for women from all years and 
                    departments of our college</p></div>
                </div>
                
            </div>
            {%elif clublist.name == "FORESE"%}
            <div id="foreseevent">
                <div class="eventlist">
                    <div><h6><a href="#">MOCK PLACEMENTS</a></h6></div>
                    <div><p>The Mock Placements is FORESE's flagship event. This annual Preparatory event is set up exclusively for pre-final 
                        year students from all departments</p></div>
                </div>
            </div>
            {%endif%}
        </div>
    </div>
{%endblock%}

templates/index.html
{%extends 'base.html'%}
{%load static%}
{%block index%}
<style>
    #clublist{
        margin: auto;
        padding: 4rem 1rem;
        list-style-type: none;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-wrap: wrap;
    }
    .container{
        width: 20rem;
        height: 26.5rem;
        background-color: white;
        min-width: 15rem;
        margin: 1rem;
        background: #FFFFFF;
        box-shadow: 0px 12px 24px rgba(18, 38, 63, 0.158);
        border-radius: 4px;   
    }
    .container a{
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        align-items: center;
        height: 100%;
    }
    .imgContainer {
        width: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        padding: 3rem 0rem;

    }
    .imgContainer img{
        width: 90%;
    }
    .clubname p {
        font-family: 'Poppins', sans-serif;
        font-size: 30px;
        font-weight: 600;
        letter-spacing: 3px;
        color: black;
    }
</style>
<ul id="clublist">
    {%for club in clublist%}
    <li class="club">
        <div class="container">
            <a href="club/{{club.name}}">
                <div class="imgContainer">
                    <img
                        src='/static/{{club.logo_url}}'
                        alt="">
                </div>
                <div class="clubname">
                    <p>{{club.name}}</p>
                </div>
            </a>
        </div>
    </li>
    {%endfor%}
</ul>
{%endblock%}

templates/login.html
{%extends 'base.html'%}
{%block signinpage%}
{% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>Message:</strong> {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
    </div>
    {% endfor %}
    <form method="post" action="" id="login-form">
        <h5>Log In to your account!</h5>
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Enter Your Username" Required>
        </div>
        <div class="form-group">
            <label for="pass1">Password</label>
            <input type="password" class="form-control" id="pass1" name="pass1" placeholder="Enter Your Password" Required>
        </div>
        <button type="submit" class="btn btn-primary">Log In</button>
        <a href="register">Register</a>
    </form>
{%endblock%}

templates/rec_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
            integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>ACE Form</title>
</head>
<body>
    <div class="container d-flex h-100">
        <div class="row justify-content-center align-self-center">
            <div class="card" style="width: 45rem;">
        
        <div class="card-body">
            <h5 class="card-title card text-center">ACE Application Form </h5>
            <p class="card text-center">Just answer a few questions<br> so that we can personalize the right experience for you.</p>
            <form >
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" id="name" placeholder="Enter Name" name="email">
                </div>
                <div class="form-group">
                    <label for="branch">Branch:</label>
                    <input type="text" class="form-control" id="branch" placeholder="Enter Branch" name="branch">
                </div>
                <div class="form-group">
                    <label for="year">Year studying:</label>
                    <input type="text" class="form-control" id="year" placeholder="Enter Year of Studying" name="year">
                </div>
                <div class="form-group">
                    <label for="section">Section:</label>
                    <input type="text" class="form-control" id="section" placeholder="Enter Section" name="section">
                </div>
                <div class="form-group">
                    <label for="phone_number">Phone number:</label>
                    <input type="number" class="form-control" id="phone_number" placeholder="Enter Phone Number" name="phone_number">
                </div>
                <div class="form-group">
                    <label for="reg_num">Registration Number:</label>
                    <input type="number" class="form-control" id="reg_num" placeholder="Enter Registration Number" name="reg_num">
                </div>
                <div class="form-group">
                    <label for="c_mid">College Mail Id:</label>
                    <input type="text" class="form-control" id="c_mid" placeholder="Enter College Mail Id" name="c_mid">
                </div>
                <div class="form-group">
                    <label for="lp">LinkedIn Profile:</label>
                    <input type="url" class="form-control" id="lp" placeholder="Enter LinkedIn url" name="lp">
                </div>
                <div class="form-group">
                    <label for="cont">What would ne your contribution for the club?</label>
                    <input type="text" class="form-control" id="cont" placeholder="Enter your contribution" name="cont">
                </div>
                <div class="form-group">
                    <label for="ev_i">Suggest an Event Idea :</label>
                    <input type="text" class="form-control" id="ev_i" placeholder="Enter your idea" name="ev_i">
                </div>
                
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>
    </div>
    </div>
    </div>
</body>
</html>

templates/register.html
{%extends 'base.html'%}
{%block register%}

{% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>Message:</strong> {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
    </div>
    {% endfor %}

    <form method="post" action="" id="register-page">
        <h5>Create your account!</h5>
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Create A Username (use only letters and numbers)" Required>
        </div>
        <div class="form-group">
            <label for="fname">First Name</label>
            <input type="text" class="form-control" id="fname" name="fname" placeholder="Enter Your First Name" Required>
        </div>
        <div class="form-group">
            <label for="lname">Last Name</label>
            <input type="text" class="form-control" id="lname" name="lname" placeholder="Enter Your Last Name" Required>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter Your Email Address" Required>
        </div>
        <div class="form-group">
            <label for="pass1">Password</label>
            <input type="password" class="form-control" id="pass1" name="pass1" placeholder="Create Your Password" Required>
        </div>
        <div class="form-group">
            <label for="pass2">Confirm Password</label>
            <input type="password" class="form-control" id="pass2" name="pass2" placeholder="Confirm Your Password" Required>
        </div>
        <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
{%endblock%}

templates/registration.html
{%extends 'base.html'%}
{%block registration%}
<style>
  #recform{
      width: 40%;
      margin: auto;
      padding: 20px;
  }
</style>
<div class="form-card">
    <div class="form-body">
      <form method="post" action="" id="recform">
        <h5>{{clubname}} Application Form</h5>
      <p>
        Just answer a few questions<br />
        so that we can personalize the right experience for you.
      </p>
        {% csrf_token %}
        <div class="form-group">
          <label for="name">Name:</label>
          <input
            type="text"
            class="form-control"
            id="name"
            placeholder="Enter Name"
            name="name"
          />
        </div>
        <div class="form-group">
          <label for="branch">Branch:</label>
          <input
            type="text"
            class="form-control"
            id="branch"
            placeholder="Enter Branch"
            name="branch"
          />
        </div>
        <div class="form-group">
          <label for="year">Year studying:</label>
          <input
            type="text"
            class="form-control"
            id="year"
            placeholder="Enter Year of Studying"
            name="year"
          />
        </div>
        <div class="form-group">
          <label for="section">Section:</label>
          <input
            type="text"
            class="form-control"
            id="section"
            placeholder="Enter Section"
            name="section"
          />
        </div>
        <div class="form-group">
          <label for="phone_number">Phone number:</label>
          <input
            type="tel"
            class="form-control"
            id="phone_number"
            placeholder="Enter Phone Number"
            name="phone_number"
          />
        </div>
        <div class="form-group">
          <label for="reg_num">Registration Number:</label>
          <input
            type="number"
            class="form-control"
            id="reg_num"
            placeholder="Enter Registration Number"
            name="reg_num"
            min="0"
          />
        </div>
        <div class="form-group">
          <label for="c_mid">College Mail Id:</label>
          <input
            type="email"
            class="form-control"
            id="c_mid"
            placeholder="Enter College Mail Id"
            name="c_mid"
          />
        </div>
        <div class="form-group">
          <label for="lp">LinkedIn Profile:</label>
          <input
            type="url"
            class="form-control"
            id="lp"
            placeholder="Enter LinkedIn url"
            name="lp"
          />
        </div>
        <button style="float: right;" type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
{%endblock%}